#!/bin/bash
# chkconfig: 2345 91 92
#         description: Saves and restores system entropy pool for \
#         higher quality random number generatio


prog=/usr/bin/supervisord
conf=/etc/supervisord.conf

# Require root to run this script.
if [[ "$(whoami)" != "root" ]]; then
     echo "Please run this script as root." >&2
     exit 1
fi

# Source function library.
#. /etc/init.d/functions
if [ ! -f /usr/bin/supervisord ]
       then
            echo "tomcat is not exit.please install."
            exit 1
fi
#This is a function for start 
function start(){
        if [ `ps -ef |grep /usr/bin/supervisord|grep -v grep|wc -l` -eq 0 ]
              then
                    $prog -c $conf
                    sleep 1
                    echo "supervisor starting..."
              else
                    echo "supervisor is already running..."
                    exit 3
        fi
}
#This is a function for stop 
function stop(){
        if [ `ps -ef |grep /usr/bin/supervisord|grep -v grep|wc -l` -ne 0  ]
                then
                        PID=`ps -ef |grep /usr/bin/supervisord|grep -v grep|awk '{print $2}'`
                        kill -9 $PID
                        PID2=`ps -ef |grep "udpserver3.py s"|grep -v grep|awk '{print $2}'`
                        kill -9 $PID2
                        [ $? -eq 0 ]&&\
                        echo "supervisor is stopping..."
                        sleep 1
                        echo "supervisor  been stoped."
                 else
                        echo "supervisor had been stoped."
                        exit 4
        fi
}
#This is a function for restart tomcat
function restart(){
        if [ `ps -ef |grep /usr/bin/supervisord |grep -v grep|wc -l` -gt 0  ]
               then
                 PID1=`ps -ef |grep /usr/bin/supervisord|grep -v grep|awk '{print $2}'`
                        kill -9 $PID1
                        PID2=`ps -ef |grep "udpserver3.py s"|grep -v grep|awk '{print $2}'`
                        kill -9 $PID2
                        [ $? -eq 0 ]&&$prog -c $conf >/dev/null 2>&1

                        [ $? -eq 0 ]&&echo "supervisord is restarting..."
                        sleep 1
                        echo "supervisor is restartted."
                else
                        $prog -c $conf >/dev/null 2>&1
                        echo "supervisord is restartted."
                        exit 5
        fi
}
#This is a function for status tomcat
function status(){
        if [ `ps -ef |grep /usr/bin/supervisord |grep -v grep|wc -l` -gt 0  ]
                then
                     echo "supervisor is running." 
                else
                      echo "supervisor is stopped." 
                      exit 5
        fi
}
case $1 in
        start)
        start
;;
        stop)
        stop
;;
        restart)
        restart
;;
        status)
        status
;;

        *)
        echo "USAG:start|stop|restart|status"
esac        

