#!/bin/bash
# chkconfig: 2345 92 92
#         description: Saves and restores system entropy pool for \
#         higher quality random number generatio

. /etc/init.d/functions
#set env
export PATH=$PATH:/bin:/sbin:/usr/sbin
export LANG="zh_CN.GB18030"
CATALANA_HOME=/home/cin-soss/local/war/apache-tomcat-9.0.13

# Require root to run this script.
if [[ "$(whoami)" != "root" ]]; then
     echo "Please run this script as root." >&2
     exit 1
fi

# Source function library.
#. /etc/init.d/functions
if [ ! -f $CATALANA_HOME/bin/startup.sh ]
       then
            echo "tomcat is not exit.please install."
fi
#This is a function for start tomcat
function start(){
        if [ `ps -ef |grep $CATALANA_HOME|grep -v grep|grep -v sh|wc -l` -eq 0 ]
              then
                    /bin/sh $CATALANA_HOME/bin/startup.sh >/dev/null 2>&1
                    [ $? -eq 0 ]&&\
                    sleep 1
                    echo "tmocat start." 
              else
                    echo "tomcat had been startted." 
        fi
}
#This is a function for stop tomcat
function stop(){
        if [ `ps -ef |grep java|grep -v grep|grep -v sh|wc -l` -gt 0  ]
                then
                        PID=`ps -ef |grep $CATALANA_HOME|grep -v grep|awk '{print $2}'`
                        kill -9 $PID
                        [ $? -eq 0 ]&&\
                        echo "tomcat is stopping..."
                        sleep 1
                        echo "tomcat  been stoped."
                 else
                        echo "tomcat had been stoped."
                        
        fi
}
#This is a function for restart tomcat
function restart(){
        if [ `ps -ef |grep java |grep -v grep|grep -v sh|wc -l` -gt 0  ];then
                 PID1=`ps -ef |grep $CATALANA_HOME|grep -v grep|awk '{print $2}'`
                        kill -9 $PID1
                        [ $? -eq 0 ]&&/bin/sh $CATALANA_HOME/bin/startup.sh >/dev/null 2>&1

                        [ $? -eq 0 ]&&echo "tomcat is restarting..."
                        sleep 1
                        echo "tomcat is restartted." 
        else
                        /bin/sh $CATALANA_HOME/bin/startup.sh >/dev/null 2>&1
                        echo "tomcat is restartted." 
        fi
}
#This is a function for status tomcat
function status(){
        if [ `ps -ef |grep $CATALANA_HOME |grep -v grep|wc -l` -gt 0  ]
                then
                     echo "tomcat is running." 
                else
                     echo "tomcat is stopped."
        fi
}
case $1 in
        start)
        start
;;
        stop)
        stop
;;
        restart)
        restart
;;
        status)
        status
;;

        *)
        echo "USAG:start|stop|restart|status"
esac        

