---
- name: Copy zabbix config file
  template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
            owner=root group=root mode=0644 backup=yes follow=yes 
- name: rm userparameter_mysql.conf
  shell: rm -rf /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
- name: copy zabbix_agentd.d.tar.gz
  copy: src=zabbix_agentd.d.tar.gz dest=/etc/zabbix/zabbix_agentd.d/
            owner=root group=root
- name: Uncompression zabbix_agentd.d.tar.gz
  shell: tar -zxf /etc/zabbix/zabbix_agentd.d/zabbix_agentd.d.tar.gz -C /etc/zabbix/zabbix_agentd.d/
- name: push agent to remote
  lineinfile:
      dest: /etc/sudoers
      regexp: "^zabbix"
      insertbefore: '^#Port'
      line: "zabbix  ALL=(ALL)       NOPASSWD: ALL"
- name: push agent to remote
  lineinfile:
      dest: /etc/sudoers
      regexp: "^[#]*Defaults    requiretty"
      line: "#Defaults    requiretty"
- name: Delete zabbix_agentd.d.tar.gz source file
  shell: rm -rf /etc/zabbix/zabbix_agentd.d/zabbix_agentd.d.tar.gz

